<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <IsPackable>false</IsPackable>
    <IsTestProject>true</IsTestProject>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="coverlet.collector" PrivateAssets="all" />
    <PackageReference Include="ClosedXML" />
    <PackageReference Include="Microsoft.AspNetCore.Mvc.Testing" />
    <PackageReference Include="Microsoft.NET.Test.Sdk" />
    <PackageReference Include="xunit" />
    <PackageReference Include="xunit.runner.visualstudio" PrivateAssets="all" />
  </ItemGroup>
  <ItemGroup>
    <Using Include="Xunit" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\..\src\Sub2ApiReport.Api\Sub2ApiReport.Api.csproj" />
    <ProjectReference Include="..\..\src\Sub2ApiReport.Infrastructure\Sub2ApiReport.Infrastructure.csproj" />
  </ItemGroup>
  <ItemGroup>
    <None Include="GoldenFiles\**\*" CopyToOutputDirectory="PreserveNewest" />
  </ItemGroup>
</Project>
