// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sub2ApiReport.Infrastructure.Persistence;

#nullable disable

namespace Sub2ApiReport.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20260827080746_AddMultiUserScope")]
    partial class AddMultiUserScope
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AdminUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AdminUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AdminUserTokens", (string)null);
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("OccurredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Notifications.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CcAddressesJson")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTestCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastTestSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignSecretCiphertext")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignSecretSuffix")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPasswordCiphertext")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPasswordSuffix")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpSecurity")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToAddressesJson")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookCiphertext")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookSuffix")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationChannels", null, t =>
                        {
                            t.HasCheckConstraint("CK_NotificationChannels_EmailExclusive", "Type = 'Email' OR (SmtpHost IS NULL AND SmtpPort IS NULL AND SmtpSecurity IS NULL AND SmtpUsername IS NULL AND FromAddress IS NULL AND FromName IS NULL AND ToAddressesJson IS NULL AND CcAddressesJson IS NULL AND SmtpPasswordCiphertext IS NULL AND SmtpPasswordSuffix IS NULL)");

                            t.HasCheckConstraint("CK_NotificationChannels_EmailFields", "Type <> 'Email' OR (SmtpHost IS NOT NULL AND SmtpPort IS NOT NULL AND SmtpSecurity IS NOT NULL AND FromAddress IS NOT NULL AND ToAddressesJson IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotificationChannels_EmailSecret", "Type <> 'Email' OR (SmtpPasswordCiphertext IS NULL AND SmtpPasswordSuffix IS NULL) OR (SmtpPasswordCiphertext IS NOT NULL AND SmtpPasswordSuffix IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotificationChannels_Name", "length(Name) >= 1");

                            t.HasCheckConstraint("CK_NotificationChannels_Revision", "Revision > 0");

                            t.HasCheckConstraint("CK_NotificationChannels_WebhookExclusive", "Type IN ('DingTalk', 'Feishu') OR (WebhookCiphertext IS NULL AND WebhookSuffix IS NULL AND SignSecretCiphertext IS NULL AND SignSecretSuffix IS NULL)");

                            t.HasCheckConstraint("CK_NotificationChannels_WebhookFields", "Type NOT IN ('DingTalk', 'Feishu') OR (WebhookCiphertext IS NOT NULL AND WebhookSuffix IS NOT NULL AND SignSecretCiphertext IS NOT NULL AND SignSecretSuffix IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.People.Person", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Code")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT")
                        .UseCollation("NOCASE");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("DisplayName")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsActive")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("Code")
                        .IsUnique();

                    b.HasIndex("IsActive", "DisplayName");

                    b.ToTable("People", null, t =>
                        {
                            t.HasCheckConstraint("CK_People_Revision", "Revision > 0");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.People.PersonApiKeyAssignment", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ExternalApiKeyId")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("PersonId")
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly>("ValidFrom")
                        .HasColumnType("TEXT");

                    b.Property<DateOnly?>("ValidTo")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalApiKeyId", "ValidFrom", "ValidTo");

                    b.HasIndex("PersonId", "ValidFrom", "ValidTo");

                    b.ToTable("PersonApiKeyAssignments", null, t =>
                        {
                            t.HasCheckConstraint("CK_PersonApiKeyAssignments_DateRange", "ValidTo IS NULL OR ValidTo >= ValidFrom");

                            t.HasCheckConstraint("CK_PersonApiKeyAssignments_Revision", "Revision > 0");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.DeliveryPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId", "PartIndex")
                        .IsUnique();

                    b.ToTable("DeliveryParts", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeliveryParts_Attempts", "Attempts >= 0");

                            t.HasCheckConstraint("CK_DeliveryParts_Index", "PartIndex >= 0 AND PartCount >= 1 AND PartIndex < PartCount");

                            t.HasCheckConstraint("CK_DeliveryParts_Status", "Status IN ('Pending', 'Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.DeliveryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("SentAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("RunId", "ChannelId")
                        .IsUnique();

                    b.ToTable("DeliveryRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeliveryRecords_Attempts", "Attempts >= 0");

                            t.HasCheckConstraint("CK_DeliveryRecords_ChannelType", "ChannelType IN ('Email', 'DingTalk', 'Feishu')");

                            t.HasCheckConstraint("CK_DeliveryRecords_Status", "Status IN ('Pending', 'Sending', 'Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.ReportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("CompletedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("ReportSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("StartedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("ReportSnapshotId", "StartedAt");

                    b.ToTable("ReportRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReportRuns_Completion", "(Status = 'Running' AND CompletedAt IS NULL) OR (Status <> 'Running' AND CompletedAt IS NOT NULL)");

                            t.HasCheckConstraint("CK_ReportRuns_Status", "Status IN ('Running', 'Succeeded', 'PartialFailed', 'Failed')");

                            t.HasCheckConstraint("CK_ReportRuns_Trigger", "Trigger = 'ManualDelivery'");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.ReportSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ConnectionRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CutoffDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedSegmentCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("GeneratedAt")
                        .HasColumnType("TEXT");

                    b.Property<long>("GeneratedAtUnixMilliseconds")
                        .HasColumnType("INTEGER");

                    b.Property<int>("KeyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PersonCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SevenDayActualCost")
                        .HasPrecision(38, 18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThirtyDayActualCost")
                        .HasPrecision(38, 18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("UnassignedSegmentCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CutoffDate", "Status");

                    b.HasIndex("GeneratedAtUnixMilliseconds", "Id");

                    b.ToTable("ReportSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReportSnapshots_ConnectionRevision", "ConnectionRevision > 0");

                            t.HasCheckConstraint("CK_ReportSnapshots_Costs", "SevenDayActualCost >= 0 AND ThirtyDayActualCost >= 0");

                            t.HasCheckConstraint("CK_ReportSnapshots_Counts", "PersonCount >= 0 AND KeyCount >= 0 AND FailedSegmentCount >= 0 AND UnassignedSegmentCount >= 0");

                            t.HasCheckConstraint("CK_ReportSnapshots_SchemaVersion", "SchemaVersion > 0");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Security.RecoveryChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId", "ExpiresAt");

                    b.ToTable("RecoveryChallenges", (string)null);
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Security.SetupChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<DateTimeOffset?>("ConsumedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("ExpiresAt")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockedUntil")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RevokedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("SetupChallenges", (string)null);
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Sub2Api.ExternalApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Sub2ApiUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Sub2ApiUserId");

                    b.HasIndex("RetiredAt", "Status", "ExternalId");

                    b.ToTable("ExternalApiKeys", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExternalApiKeys_ExternalId", "ExternalId > 0");

                            t.HasCheckConstraint("CK_ExternalApiKeys_GroupId", "GroupId IS NULL OR GroupId > 0");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Sub2Api.Sub2ApiConnection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminApiKeyCiphertext")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminApiKeySuffix")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CodexGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastSynchronizedAt")
                        .HasColumnType("TEXT");

                    b.Property<int?>("LastSynchronizedKeyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastSynchronizedUserCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastTestCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastTestSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LastTestedAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("LastUsersSynchronizedAt")
                        .HasColumnType("TEXT");

                    b.Property<long?>("LegacyUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("UserScopeMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("SelectedUsers");

                    b.HasKey("Id");

                    b.ToTable("Sub2ApiConnections", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sub2ApiConnections_CodexGroupId", "CodexGroupId IS NULL OR CodexGroupId > 0");

                            t.HasCheckConstraint("CK_Sub2ApiConnections_Revision", "Revision > 0");

                            t.HasCheckConstraint("CK_Sub2ApiConnections_Singleton", "Id = 1");

                            t.HasCheckConstraint("CK_Sub2ApiConnections_UserId", "UserId IS NULL OR UserId > 0");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Sub2Api.Sub2ApiUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailSnapshot")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset>("LastSeenAt")
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("RetiredAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("RetiredAt", "Status", "IsSelected");

                    b.ToTable("Sub2ApiUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sub2ApiUsers_ExternalId", "ExternalId > 0");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.System.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupRetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("InitializedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseChannel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportRetentionMonths")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset?>("UpdatedAt")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackupRetentionCount = 10,
                            LogLevel = "Information",
                            ReleaseChannel = "stable",
                            ReportConcurrency = 4,
                            ReportRetentionMonths = 12,
                            Revision = 1L,
                            Timezone = "Asia/Shanghai"
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Infrastructure.Identity.Administrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<DateTimeOffset>("CreatedAt")
                        .HasColumnType("TEXT");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("SingletonKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SingletonKey")
                        .IsUnique();

                    b.ToTable("AdminUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AdminUsers_SingletonKey", "SingletonKey = 1");
                        });
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Sub2ApiReport.Infrastructure.Identity.Administrator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Sub2ApiReport.Infrastructure.Identity.Administrator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Sub2ApiReport.Infrastructure.Identity.Administrator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.People.PersonApiKeyAssignment", b =>
                {
                    b.HasOne("Sub2ApiReport.Domain.Sub2Api.ExternalApiKey", "ExternalApiKey")
                        .WithMany()
                        .HasForeignKey("ExternalApiKeyId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sub2ApiReport.Domain.People.Person", "Person")
                        .WithMany()
                        .HasForeignKey("PersonId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("ExternalApiKey");

                    b.Navigation("Person");
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.DeliveryPart", b =>
                {
                    b.HasOne("Sub2ApiReport.Domain.Reports.DeliveryRecord", "Delivery")
                        .WithMany("Parts")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.DeliveryRecord", b =>
                {
                    b.HasOne("Sub2ApiReport.Domain.Notifications.NotificationChannel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sub2ApiReport.Domain.Reports.ReportRun", "Run")
                        .WithMany("Deliveries")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.ReportRun", b =>
                {
                    b.HasOne("Sub2ApiReport.Domain.Reports.ReportSnapshot", null)
                        .WithMany()
                        .HasForeignKey("ReportSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Security.RecoveryChallenge", b =>
                {
                    b.HasOne("Sub2ApiReport.Infrastructure.Identity.Administrator", null)
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Sub2Api.ExternalApiKey", b =>
                {
                    b.HasOne("Sub2ApiReport.Domain.Sub2Api.Sub2ApiUser", "Sub2ApiUser")
                        .WithMany()
                        .HasForeignKey("Sub2ApiUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sub2ApiUser");
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.DeliveryRecord", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.ReportRun", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
