// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Sub2ApiReport.Infrastructure.Persistence;

#nullable disable

namespace Sub2ApiReport.Infrastructure.Persistence.Migrations
{
    [DbContext(typeof(ReportDbContext))]
    [Migration("20260828025413_CompleteUnixTimeStorage")]
    partial class CompleteUnixTimeStorage
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "10.0.10");

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzBlobTrigger", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasColumnType("text")
                        .HasColumnName("SCHED_NAME");

                    b.Property<string>("TriggerName")
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_NAME");

                    b.Property<string>("TriggerGroup")
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_GROUP");

                    b.Property<byte[]>("BlobData")
                        .HasColumnType("bytea")
                        .HasColumnName("BLOB_DATA");

                    b.HasKey("SchedulerName", "TriggerName", "TriggerGroup");

                    b.ToTable("QRTZ_BLOB_TRIGGERS", (string)null);
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzCalendar", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasColumnType("text")
                        .HasColumnName("SCHED_NAME");

                    b.Property<string>("CalendarName")
                        .HasColumnType("text")
                        .HasColumnName("CALENDAR_NAME");

                    b.Property<byte[]>("Calendar")
                        .IsRequired()
                        .HasColumnType("bytea")
                        .HasColumnName("CALENDAR");

                    b.HasKey("SchedulerName", "CalendarName");

                    b.ToTable("QRTZ_CALENDARS", (string)null);
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzCronTrigger", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasColumnType("text")
                        .HasColumnName("SCHED_NAME");

                    b.Property<string>("TriggerName")
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_NAME");

                    b.Property<string>("TriggerGroup")
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_GROUP");

                    b.Property<string>("CronExpression")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("CRON_EXPRESSION");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text")
                        .HasColumnName("TIME_ZONE_ID");

                    b.HasKey("SchedulerName", "TriggerName", "TriggerGroup");

                    b.ToTable("QRTZ_CRON_TRIGGERS", (string)null);
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzFiredTrigger", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasColumnType("text")
                        .HasColumnName("SCHED_NAME");

                    b.Property<string>("EntryId")
                        .HasColumnType("text")
                        .HasColumnName("ENTRY_ID");

                    b.Property<long>("FiredTime")
                        .HasColumnType("bigint")
                        .HasColumnName("FIRED_TIME");

                    b.Property<string>("InstanceName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("INSTANCE_NAME");

                    b.Property<bool>("IsNonConcurrent")
                        .HasColumnType("bool")
                        .HasColumnName("IS_NONCONCURRENT");

                    b.Property<string>("JobGroup")
                        .HasColumnType("text")
                        .HasColumnName("JOB_GROUP");

                    b.Property<string>("JobName")
                        .HasColumnType("text")
                        .HasColumnName("JOB_NAME");

                    b.Property<int>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("PRIORITY");

                    b.Property<bool?>("RequestsRecovery")
                        .HasColumnType("bool")
                        .HasColumnName("REQUESTS_RECOVERY");

                    b.Property<long>("ScheduledTime")
                        .HasColumnType("bigint")
                        .HasColumnName("SCHED_TIME");

                    b.Property<string>("State")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("STATE");

                    b.Property<string>("TriggerGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_GROUP");

                    b.Property<string>("TriggerName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_NAME");

                    b.HasKey("SchedulerName", "EntryId");

                    b.HasIndex("InstanceName")
                        .HasDatabaseName("IDX_QRTZ_FT_TRIG_INST_NAME");

                    b.HasIndex("JobGroup")
                        .HasDatabaseName("IDX_QRTZ_FT_JOB_GROUP");

                    b.HasIndex("JobName")
                        .HasDatabaseName("IDX_QRTZ_FT_JOB_NAME");

                    b.HasIndex("RequestsRecovery")
                        .HasDatabaseName("IDX_QRTZ_FT_JOB_REQ_RECOVERY");

                    b.HasIndex("TriggerGroup")
                        .HasDatabaseName("IDX_QRTZ_FT_TRIG_GROUP");

                    b.HasIndex("TriggerName")
                        .HasDatabaseName("IDX_QRTZ_FT_TRIG_NAME");

                    b.HasIndex("SchedulerName", "TriggerName", "TriggerGroup")
                        .HasDatabaseName("IDX_QRTZ_FT_TRIG_NM_GP");

                    b.ToTable("QRTZ_FIRED_TRIGGERS", (string)null);
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzJobDetail", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasColumnType("text")
                        .HasColumnName("SCHED_NAME");

                    b.Property<string>("JobName")
                        .HasColumnType("text")
                        .HasColumnName("JOB_NAME");

                    b.Property<string>("JobGroup")
                        .HasColumnType("text")
                        .HasColumnName("JOB_GROUP");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<bool>("IsDurable")
                        .HasColumnType("bool")
                        .HasColumnName("IS_DURABLE");

                    b.Property<bool>("IsNonConcurrent")
                        .HasColumnType("bool")
                        .HasColumnName("IS_NONCONCURRENT");

                    b.Property<bool>("IsUpdateData")
                        .HasColumnType("bool")
                        .HasColumnName("IS_UPDATE_DATA");

                    b.Property<string>("JobClassName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("JOB_CLASS_NAME");

                    b.Property<byte[]>("JobData")
                        .HasColumnType("bytea")
                        .HasColumnName("JOB_DATA");

                    b.Property<bool>("RequestsRecovery")
                        .HasColumnType("bool")
                        .HasColumnName("REQUESTS_RECOVERY");

                    b.HasKey("SchedulerName", "JobName", "JobGroup");

                    b.HasIndex("RequestsRecovery")
                        .HasDatabaseName("IDX_QRTZ_J_REQ_RECOVERY");

                    b.ToTable("QRTZ_JOB_DETAILS", (string)null);
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzLock", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasColumnType("text")
                        .HasColumnName("SCHED_NAME");

                    b.Property<string>("LockName")
                        .HasColumnType("text")
                        .HasColumnName("LOCK_NAME");

                    b.HasKey("SchedulerName", "LockName");

                    b.ToTable("QRTZ_LOCKS", (string)null);
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzPausedTriggerGroup", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasColumnType("text")
                        .HasColumnName("SCHED_NAME");

                    b.Property<string>("TriggerGroup")
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_GROUP");

                    b.HasKey("SchedulerName", "TriggerGroup");

                    b.ToTable("QRTZ_PAUSED_TRIGGER_GRPS", (string)null);
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzSchedulerState", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasColumnType("text")
                        .HasColumnName("SCHED_NAME");

                    b.Property<string>("InstanceName")
                        .HasColumnType("text")
                        .HasColumnName("INSTANCE_NAME");

                    b.Property<long>("CheckInInterval")
                        .HasColumnType("bigint")
                        .HasColumnName("CHECKIN_INTERVAL");

                    b.Property<long>("LastCheckInTime")
                        .HasColumnType("bigint")
                        .HasColumnName("LAST_CHECKIN_TIME");

                    b.HasKey("SchedulerName", "InstanceName");

                    b.ToTable("QRTZ_SCHEDULER_STATE", (string)null);
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzSimplePropertyTrigger", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasColumnType("text")
                        .HasColumnName("SCHED_NAME");

                    b.Property<string>("TriggerName")
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_NAME");

                    b.Property<string>("TriggerGroup")
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_GROUP");

                    b.Property<bool?>("BooleanProperty1")
                        .HasColumnType("bool")
                        .HasColumnName("BOOL_PROP_1");

                    b.Property<bool?>("BooleanProperty2")
                        .HasColumnType("bool")
                        .HasColumnName("BOOL_PROP_2");

                    b.Property<decimal?>("DecimalProperty1")
                        .HasColumnType("numeric")
                        .HasColumnName("DEC_PROP_1");

                    b.Property<decimal?>("DecimalProperty2")
                        .HasColumnType("numeric")
                        .HasColumnName("DEC_PROP_2");

                    b.Property<int?>("IntegerProperty1")
                        .HasColumnType("integer")
                        .HasColumnName("INT_PROP_1");

                    b.Property<int?>("IntegerProperty2")
                        .HasColumnType("integer")
                        .HasColumnName("INT_PROP_2");

                    b.Property<long?>("LongProperty1")
                        .HasColumnType("bigint")
                        .HasColumnName("LONG_PROP_1");

                    b.Property<long?>("LongProperty2")
                        .HasColumnType("bigint")
                        .HasColumnName("LONG_PROP_2");

                    b.Property<string>("StringProperty1")
                        .HasColumnType("text")
                        .HasColumnName("STR_PROP_1");

                    b.Property<string>("StringProperty2")
                        .HasColumnType("text")
                        .HasColumnName("STR_PROP_2");

                    b.Property<string>("StringProperty3")
                        .HasColumnType("text")
                        .HasColumnName("STR_PROP_3");

                    b.Property<string>("TimeZoneId")
                        .HasColumnType("text")
                        .HasColumnName("TIME_ZONE_ID");

                    b.HasKey("SchedulerName", "TriggerName", "TriggerGroup");

                    b.ToTable("QRTZ_SIMPROP_TRIGGERS", (string)null);
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzSimpleTrigger", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasColumnType("text")
                        .HasColumnName("SCHED_NAME");

                    b.Property<string>("TriggerName")
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_NAME");

                    b.Property<string>("TriggerGroup")
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_GROUP");

                    b.Property<long>("RepeatCount")
                        .HasColumnType("bigint")
                        .HasColumnName("REPEAT_COUNT");

                    b.Property<long>("RepeatInterval")
                        .HasColumnType("bigint")
                        .HasColumnName("REPEAT_INTERVAL");

                    b.Property<long>("TimesTriggered")
                        .HasColumnType("bigint")
                        .HasColumnName("TIMES_TRIGGERED");

                    b.HasKey("SchedulerName", "TriggerName", "TriggerGroup");

                    b.ToTable("QRTZ_SIMPLE_TRIGGERS", (string)null);
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzTrigger", b =>
                {
                    b.Property<string>("SchedulerName")
                        .HasColumnType("text")
                        .HasColumnName("SCHED_NAME");

                    b.Property<string>("TriggerName")
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_NAME");

                    b.Property<string>("TriggerGroup")
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_GROUP");

                    b.Property<string>("CalendarName")
                        .HasColumnType("text")
                        .HasColumnName("CALENDAR_NAME");

                    b.Property<string>("Description")
                        .HasColumnType("text")
                        .HasColumnName("DESCRIPTION");

                    b.Property<long?>("EndTime")
                        .HasColumnType("bigint")
                        .HasColumnName("END_TIME");

                    b.Property<byte[]>("JobData")
                        .HasColumnType("bytea")
                        .HasColumnName("JOB_DATA");

                    b.Property<string>("JobGroup")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("JOB_GROUP");

                    b.Property<string>("JobName")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("JOB_NAME");

                    b.Property<short?>("MisfireInstruction")
                        .HasColumnType("smallint")
                        .HasColumnName("MISFIRE_INSTR");

                    b.Property<long?>("MisfireOriginalFireTime")
                        .HasColumnType("bigint")
                        .HasColumnName("MISFIRE_ORIG_FIRE_TIME");

                    b.Property<long?>("NextFireTime")
                        .HasColumnType("bigint")
                        .HasColumnName("NEXT_FIRE_TIME");

                    b.Property<long?>("PreviousFireTime")
                        .HasColumnType("bigint")
                        .HasColumnName("PREV_FIRE_TIME");

                    b.Property<int?>("Priority")
                        .HasColumnType("integer")
                        .HasColumnName("PRIORITY");

                    b.Property<long>("StartTime")
                        .HasColumnType("bigint")
                        .HasColumnName("START_TIME");

                    b.Property<string>("TriggerState")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_STATE");

                    b.Property<string>("TriggerType")
                        .IsRequired()
                        .HasColumnType("text")
                        .HasColumnName("TRIGGER_TYPE");

                    b.HasKey("SchedulerName", "TriggerName", "TriggerGroup");

                    b.HasIndex("NextFireTime")
                        .HasDatabaseName("IDX_QRTZ_T_NEXT_FIRE_TIME");

                    b.HasIndex("TriggerState")
                        .HasDatabaseName("IDX_QRTZ_T_STATE");

                    b.HasIndex("NextFireTime", "TriggerState")
                        .HasDatabaseName("IDX_QRTZ_T_NFT_ST");

                    b.HasIndex("SchedulerName", "JobName", "JobGroup");

                    b.ToTable("QRTZ_TRIGGERS", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ClaimType")
                        .HasColumnType("TEXT");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("AdminUserClaims", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("TEXT");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("TEXT");

                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("AdminUserLogins", (string)null);
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.Property<Guid>("UserId")
                        .HasColumnType("TEXT");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("TEXT");

                    b.Property<string>("Name")
                        .HasColumnType("TEXT");

                    b.Property<string>("Value")
                        .HasColumnType("TEXT");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("AdminUserTokens", (string)null);
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Audit.AuditEvent", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("Action")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Actor")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("CorrelationId")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("MetadataJson")
                        .HasMaxLength(4000)
                        .HasColumnType("TEXT");

                    b.Property<long>("OccurredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("OccurredAtUnixMilliseconds");

                    b.Property<string>("Result")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Target")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("OccurredAt");

                    b.ToTable("AuditEvents", (string)null);
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Notifications.NotificationChannel", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CcAddressesJson")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAtUnixMilliseconds");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("FromAddress")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("FromName")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<string>("LastTestCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastTestSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastTestedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastTestedAtUnixMilliseconds");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("SignSecretCiphertext")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("SignSecretSuffix")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpHost")
                        .HasMaxLength(255)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPasswordCiphertext")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpPasswordSuffix")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<int?>("SmtpPort")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SmtpSecurity")
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("SmtpUsername")
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<string>("ToAddressesJson")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAtUnixMilliseconds");

                    b.Property<string>("WebhookCiphertext")
                        .HasMaxLength(4096)
                        .HasColumnType("TEXT");

                    b.Property<string>("WebhookSuffix")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("NotificationChannels", null, t =>
                        {
                            t.HasCheckConstraint("CK_NotificationChannels_EmailExclusive", "Type = 'Email' OR (SmtpHost IS NULL AND SmtpPort IS NULL AND SmtpSecurity IS NULL AND SmtpUsername IS NULL AND FromAddress IS NULL AND FromName IS NULL AND ToAddressesJson IS NULL AND CcAddressesJson IS NULL AND SmtpPasswordCiphertext IS NULL AND SmtpPasswordSuffix IS NULL)");

                            t.HasCheckConstraint("CK_NotificationChannels_EmailFields", "Type <> 'Email' OR (SmtpHost IS NOT NULL AND SmtpPort IS NOT NULL AND SmtpSecurity IS NOT NULL AND FromAddress IS NOT NULL AND ToAddressesJson IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotificationChannels_EmailSecret", "Type <> 'Email' OR (SmtpPasswordCiphertext IS NULL AND SmtpPasswordSuffix IS NULL) OR (SmtpPasswordCiphertext IS NOT NULL AND SmtpPasswordSuffix IS NOT NULL)");

                            t.HasCheckConstraint("CK_NotificationChannels_Name", "length(Name) >= 1");

                            t.HasCheckConstraint("CK_NotificationChannels_Revision", "Revision > 0");

                            t.HasCheckConstraint("CK_NotificationChannels_WebhookExclusive", "Type IN ('DingTalk', 'Feishu') OR (WebhookCiphertext IS NULL AND WebhookSuffix IS NULL AND SignSecretCiphertext IS NULL AND SignSecretSuffix IS NULL)");

                            t.HasCheckConstraint("CK_NotificationChannels_WebhookFields", "Type NOT IN ('DingTalk', 'Feishu') OR (WebhookCiphertext IS NOT NULL AND WebhookSuffix IS NOT NULL AND SignSecretCiphertext IS NOT NULL AND SignSecretSuffix IS NOT NULL)");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.DeliveryPart", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("DeliveryId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<int>("PartCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("PartIndex")
                        .HasColumnType("INTEGER");

                    b.Property<string>("PayloadHash")
                        .IsRequired()
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<long?>("SentAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SentAtUnixMilliseconds");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DeliveryId", "PartIndex")
                        .IsUnique();

                    b.ToTable("DeliveryParts", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeliveryParts_Attempts", "Attempts >= 0");

                            t.HasCheckConstraint("CK_DeliveryParts_Index", "PartIndex >= 0 AND PartCount >= 1 AND PartIndex < PartCount");

                            t.HasCheckConstraint("CK_DeliveryParts_Status", "Status IN ('Pending', 'Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.DeliveryRecord", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempts")
                        .HasColumnType("INTEGER");

                    b.Property<Guid>("ChannelId")
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelName")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("ChannelType")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("PayloadHash")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<Guid>("RunId")
                        .HasColumnType("TEXT");

                    b.Property<long?>("SentAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("SentAtUnixMilliseconds");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ChannelId");

                    b.HasIndex("RunId", "ChannelId")
                        .IsUnique();

                    b.ToTable("DeliveryRecords", null, t =>
                        {
                            t.HasCheckConstraint("CK_DeliveryRecords_Attempts", "Attempts >= 0");

                            t.HasCheckConstraint("CK_DeliveryRecords_ChannelType", "ChannelType IN ('Email', 'DingTalk', 'Feishu')");

                            t.HasCheckConstraint("CK_DeliveryRecords_Status", "Status IN ('Pending', 'Sending', 'Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.ReportGenerationRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CompletedAtUnixMilliseconds");

                    b.Property<long>("ConnectionRevision")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReportRunId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("ReportSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<string>("Stage")
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StartedAtUnixMilliseconds");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ReportRunId")
                        .IsUnique();

                    b.HasIndex("Status");

                    b.HasIndex("StartedAt", "Id");

                    b.ToTable("ReportGenerationRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReportGenerationRuns_Status", "Status IN ('Running', 'Succeeded', 'Failed')");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.ReportRun", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("Attempt")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER")
                        .HasDefaultValue(1);

                    b.Property<long?>("CollectingAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CollectingAtUnixMilliseconds");

                    b.Property<long?>("CompletedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CompletedAtUnixMilliseconds");

                    b.Property<long?>("DeliveringAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("DeliveringAtUnixMilliseconds");

                    b.Property<string>("ErrorCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<string>("ErrorMessage")
                        .HasMaxLength(512)
                        .HasColumnType("TEXT");

                    b.Property<string>("IdempotencyKey")
                        .HasMaxLength(128)
                        .HasColumnType("TEXT");

                    b.Property<bool>("OutcomeUnknownConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly?>("PeriodEnd")
                        .HasColumnType("TEXT");

                    b.Property<long?>("RenderingAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RenderingAtUnixMilliseconds");

                    b.Property<Guid?>("ReportSnapshotId")
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("RetryOfRunId")
                        .HasColumnType("TEXT");

                    b.Property<int?>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("ScheduleRevision")
                        .HasColumnType("INTEGER");

                    b.Property<long>("StartedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("StartedAtUnixMilliseconds");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("IdempotencyKey")
                        .IsUnique();

                    b.HasIndex("RetryOfRunId");

                    b.HasIndex("ReportSnapshotId", "StartedAt");

                    b.HasIndex("ScheduleId", "StartedAt");

                    b.ToTable("ReportRuns", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReportRuns_Attempt", "Attempt > 0");

                            t.HasCheckConstraint("CK_ReportRuns_Completion", "(Status IN ('Succeeded', 'PartialFailed', 'Failed') AND CompletedAtUnixMilliseconds IS NOT NULL) OR (Status NOT IN ('Succeeded', 'PartialFailed', 'Failed') AND CompletedAtUnixMilliseconds IS NULL)");

                            t.HasCheckConstraint("CK_ReportRuns_Idempotency", "Trigger <> 'Scheduled' OR IdempotencyKey IS NOT NULL");

                            t.HasCheckConstraint("CK_ReportRuns_ScheduleMetadata", "Trigger = 'ManualDelivery' OR (ScheduleId IS NOT NULL AND ScheduleRevision > 0 AND PeriodEnd IS NOT NULL AND Timezone IS NOT NULL)");

                            t.HasCheckConstraint("CK_ReportRuns_Status", "Status IN ('Running', 'Queued', 'Collecting', 'Rendering', 'Delivering', 'Succeeded', 'PartialFailed', 'Failed')");

                            t.HasCheckConstraint("CK_ReportRuns_Trigger", "Trigger IN ('ManualDelivery', 'Scheduled', 'ManualScheduled', 'Retry')");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.ReportSchedule", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("DayOfMonth")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Enabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LocalTime")
                        .IsRequired()
                        .HasMaxLength(5)
                        .HasColumnType("TEXT");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAtUnixMilliseconds");

                    b.HasKey("Id");

                    b.ToTable("ReportSchedules", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReportSchedules_DayOfMonth", "DayOfMonth BETWEEN 1 AND 28");

                            t.HasCheckConstraint("CK_ReportSchedules_LocalTime", "length(LocalTime) = 5");

                            t.HasCheckConstraint("CK_ReportSchedules_Revision", "Revision > 0");

                            t.HasCheckConstraint("CK_ReportSchedules_Singleton", "Id = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            DayOfMonth = 1,
                            Enabled = false,
                            LocalTime = "09:00",
                            Revision = 1L,
                            Timezone = "Asia/Shanghai"
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.ReportSnapshot", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("CanonicalJson")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<long>("ConnectionRevision")
                        .HasColumnType("INTEGER");

                    b.Property<DateOnly>("CutoffDate")
                        .HasColumnType("TEXT");

                    b.Property<int>("FailedRangeCount")
                        .HasColumnType("INTEGER");

                    b.Property<long>("GeneratedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("GeneratedAtUnixMilliseconds");

                    b.Property<int>("KeyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int>("SchemaVersion")
                        .HasColumnType("INTEGER");

                    b.Property<decimal>("SevenDayActualCost")
                        .HasPrecision(38, 18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<decimal>("ThirtyDayActualCost")
                        .HasPrecision(38, 18)
                        .HasColumnType("TEXT");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<string>("Trigger")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("UserCount")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.HasIndex("CutoffDate", "Status");

                    b.HasIndex("GeneratedAt", "Id");

                    b.ToTable("ReportSnapshots", null, t =>
                        {
                            t.HasCheckConstraint("CK_ReportSnapshots_ConnectionRevision", "ConnectionRevision > 0");

                            t.HasCheckConstraint("CK_ReportSnapshots_Costs", "SevenDayActualCost >= 0 AND ThirtyDayActualCost >= 0");

                            t.HasCheckConstraint("CK_ReportSnapshots_Counts", "UserCount >= 0 AND KeyCount >= 0 AND FailedRangeCount >= 0");

                            t.HasCheckConstraint("CK_ReportSnapshots_SchemaVersion", "SchemaVersion > 0");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Security.RecoveryChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("AdministratorId")
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long?>("ConsumedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ConsumedAtUnixMilliseconds");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAtUnixMilliseconds");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ExpiresAtUnixMilliseconds");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockedUntil")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LockedUntilUnixMilliseconds");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RevokedAtUnixMilliseconds");

                    b.HasKey("Id");

                    b.HasIndex("AdministratorId", "ExpiresAt");

                    b.ToTable("RecoveryChallenges", (string)null);
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Security.SetupChallenge", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<byte[]>("CodeHash")
                        .IsRequired()
                        .HasColumnType("BLOB");

                    b.Property<long?>("ConsumedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ConsumedAtUnixMilliseconds");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAtUnixMilliseconds");

                    b.Property<long>("ExpiresAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("ExpiresAtUnixMilliseconds");

                    b.Property<int>("FailedAttempts")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockedUntil")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LockedUntilUnixMilliseconds");

                    b.Property<long?>("RevokedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RevokedAtUnixMilliseconds");

                    b.HasKey("Id");

                    b.HasIndex("ExpiresAt");

                    b.ToTable("SetupChallenges", (string)null);
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Sub2Api.ExternalApiKey", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<long>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("GroupId")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastSeenAtUnixMilliseconds");

                    b.Property<long?>("LastUsedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastUsedAtUnixMilliseconds");

                    b.Property<string>("NameSnapshot")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.Property<long?>("RetiredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RetiredAtUnixMilliseconds");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<Guid?>("Sub2ApiUserId")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("Sub2ApiUserId");

                    b.HasIndex("RetiredAt", "Status", "ExternalId");

                    b.ToTable("ExternalApiKeys", null, t =>
                        {
                            t.HasCheckConstraint("CK_ExternalApiKeys_ExternalId", "ExternalId > 0");

                            t.HasCheckConstraint("CK_ExternalApiKeys_GroupId", "GroupId IS NULL OR GroupId > 0");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Sub2Api.Sub2ApiConnection", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<string>("AdminApiKeyCiphertext")
                        .HasMaxLength(16384)
                        .HasColumnType("TEXT");

                    b.Property<string>("AdminApiKeySuffix")
                        .HasMaxLength(8)
                        .HasColumnType("TEXT");

                    b.Property<string>("BaseUrl")
                        .IsRequired()
                        .HasMaxLength(2048)
                        .HasColumnType("TEXT");

                    b.Property<long?>("CodexGroupId")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastSynchronizedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastSynchronizedAtUnixMilliseconds");

                    b.Property<int?>("LastSynchronizedKeyCount")
                        .HasColumnType("INTEGER");

                    b.Property<int?>("LastSynchronizedUserCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("LastTestCode")
                        .HasMaxLength(64)
                        .HasColumnType("TEXT");

                    b.Property<bool?>("LastTestSucceeded")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LastTestedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastTestedAtUnixMilliseconds");

                    b.Property<long?>("LastUsersSynchronizedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastUsersSynchronizedAtUnixMilliseconds");

                    b.Property<long?>("LegacyUserId")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UserId");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<long>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAtUnixMilliseconds");

                    b.Property<string>("UserScopeMode")
                        .IsRequired()
                        .ValueGeneratedOnAdd()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT")
                        .HasDefaultValue("SelectedUsers");

                    b.HasKey("Id");

                    b.ToTable("Sub2ApiConnections", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sub2ApiConnections_CodexGroupId", "CodexGroupId IS NULL OR CodexGroupId > 0");

                            t.HasCheckConstraint("CK_Sub2ApiConnections_Revision", "Revision > 0");

                            t.HasCheckConstraint("CK_Sub2ApiConnections_Singleton", "Id = 1");

                            t.HasCheckConstraint("CK_Sub2ApiConnections_UserId", "UserId IS NULL OR UserId > 0");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Sub2Api.Sub2ApiUser", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<string>("EmailSnapshot")
                        .IsRequired()
                        .HasMaxLength(320)
                        .HasColumnType("TEXT");

                    b.Property<long>("ExternalId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsSelected")
                        .HasColumnType("INTEGER");

                    b.Property<long>("LastSeenAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LastSeenAtUnixMilliseconds");

                    b.Property<long?>("RetiredAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("RetiredAtUnixMilliseconds");

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<string>("UsernameSnapshot")
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("ExternalId")
                        .IsUnique();

                    b.HasIndex("RetiredAt", "Status", "IsSelected");

                    b.ToTable("Sub2ApiUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_Sub2ApiUsers_ExternalId", "ExternalId > 0");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.System.SystemSetting", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<int>("BackupRetentionCount")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("InitializedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("InitializedAtUnixMilliseconds");

                    b.Property<string>("LogLevel")
                        .IsRequired()
                        .HasMaxLength(16)
                        .HasColumnType("TEXT");

                    b.Property<string>("ReleaseChannel")
                        .IsRequired()
                        .HasMaxLength(32)
                        .HasColumnType("TEXT");

                    b.Property<int>("ReportConcurrency")
                        .HasColumnType("INTEGER");

                    b.Property<int>("ReportRetentionMonths")
                        .HasColumnType("INTEGER");

                    b.Property<long>("Revision")
                        .IsConcurrencyToken()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Timezone")
                        .IsRequired()
                        .HasMaxLength(100)
                        .HasColumnType("TEXT");

                    b.Property<long?>("UpdatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("UpdatedAtUnixMilliseconds");

                    b.HasKey("Id");

                    b.ToTable("SystemSettings", (string)null);

                    b.HasData(
                        new
                        {
                            Id = 1,
                            BackupRetentionCount = 10,
                            LogLevel = "Information",
                            ReleaseChannel = "stable",
                            ReportConcurrency = 4,
                            ReportRetentionMonths = 12,
                            Revision = 1L,
                            Timezone = "Asia/Shanghai"
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Infrastructure.Identity.Administrator", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("TEXT");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("TEXT");

                    b.Property<long>("CreatedAt")
                        .HasColumnType("INTEGER")
                        .HasColumnName("CreatedAtUnixMilliseconds");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<long?>("LockoutEnd")
                        .HasColumnType("INTEGER")
                        .HasColumnName("LockoutEndUnixMilliseconds");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("TEXT");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("TEXT");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("INTEGER");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("TEXT");

                    b.Property<int>("SingletonKey")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("INTEGER");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .HasDatabaseName("EmailIndex");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex");

                    b.HasIndex("SingletonKey")
                        .IsUnique();

                    b.ToTable("AdminUsers", null, t =>
                        {
                            t.HasCheckConstraint("CK_AdminUsers_SingletonKey", "SingletonKey = 1");
                        });
                });

            modelBuilder.Entity("Sub2ApiReport.Infrastructure.Persistence.UnixTimeMigrationState", b =>
                {
                    b.Property<int>("Id")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("Completed")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("UnixTimeMigrationState", null, t =>
                        {
                            t.HasCheckConstraint("CK_UnixTimeMigrationState_Completed", "Completed = 1");
                        });

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Completed = true
                        });
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzBlobTrigger", b =>
                {
                    b.HasOne("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzTrigger", "Trigger")
                        .WithMany("BlobTriggers")
                        .HasForeignKey("SchedulerName", "TriggerName", "TriggerGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzCronTrigger", b =>
                {
                    b.HasOne("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzTrigger", "Trigger")
                        .WithMany("CronTriggers")
                        .HasForeignKey("SchedulerName", "TriggerName", "TriggerGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzSimplePropertyTrigger", b =>
                {
                    b.HasOne("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzTrigger", "Trigger")
                        .WithMany("SimplePropertyTriggers")
                        .HasForeignKey("SchedulerName", "TriggerName", "TriggerGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzSimpleTrigger", b =>
                {
                    b.HasOne("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzTrigger", "Trigger")
                        .WithMany("SimpleTriggers")
                        .HasForeignKey("SchedulerName", "TriggerName", "TriggerGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Trigger");
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzTrigger", b =>
                {
                    b.HasOne("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzJobDetail", "JobDetail")
                        .WithMany("Triggers")
                        .HasForeignKey("SchedulerName", "JobName", "JobGroup")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("JobDetail");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<System.Guid>", b =>
                {
                    b.HasOne("Sub2ApiReport.Infrastructure.Identity.Administrator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<System.Guid>", b =>
                {
                    b.HasOne("Sub2ApiReport.Infrastructure.Identity.Administrator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<System.Guid>", b =>
                {
                    b.HasOne("Sub2ApiReport.Infrastructure.Identity.Administrator", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.DeliveryPart", b =>
                {
                    b.HasOne("Sub2ApiReport.Domain.Reports.DeliveryRecord", "Delivery")
                        .WithMany("Parts")
                        .HasForeignKey("DeliveryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Delivery");
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.DeliveryRecord", b =>
                {
                    b.HasOne("Sub2ApiReport.Domain.Notifications.NotificationChannel", null)
                        .WithMany()
                        .HasForeignKey("ChannelId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Sub2ApiReport.Domain.Reports.ReportRun", "Run")
                        .WithMany("Deliveries")
                        .HasForeignKey("RunId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Run");
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.ReportGenerationRun", b =>
                {
                    b.HasOne("Sub2ApiReport.Domain.Reports.ReportRun", null)
                        .WithMany()
                        .HasForeignKey("ReportRunId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.ReportRun", b =>
                {
                    b.HasOne("Sub2ApiReport.Domain.Reports.ReportSnapshot", null)
                        .WithMany()
                        .HasForeignKey("ReportSnapshotId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sub2ApiReport.Domain.Reports.ReportRun", null)
                        .WithMany()
                        .HasForeignKey("RetryOfRunId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Sub2ApiReport.Domain.Reports.ReportSchedule", null)
                        .WithMany()
                        .HasForeignKey("ScheduleId")
                        .OnDelete(DeleteBehavior.Restrict);
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Security.RecoveryChallenge", b =>
                {
                    b.HasOne("Sub2ApiReport.Infrastructure.Identity.Administrator", null)
                        .WithMany()
                        .HasForeignKey("AdministratorId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Sub2Api.ExternalApiKey", b =>
                {
                    b.HasOne("Sub2ApiReport.Domain.Sub2Api.Sub2ApiUser", "Sub2ApiUser")
                        .WithMany()
                        .HasForeignKey("Sub2ApiUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Sub2ApiUser");
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzJobDetail", b =>
                {
                    b.Navigation("Triggers");
                });

            modelBuilder.Entity("AppAny.Quartz.EntityFrameworkCore.Migrations.QuartzTrigger", b =>
                {
                    b.Navigation("BlobTriggers");

                    b.Navigation("CronTriggers");

                    b.Navigation("SimplePropertyTriggers");

                    b.Navigation("SimpleTriggers");
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.DeliveryRecord", b =>
                {
                    b.Navigation("Parts");
                });

            modelBuilder.Entity("Sub2ApiReport.Domain.Reports.ReportRun", b =>
                {
                    b.Navigation("Deliveries");
                });
#pragma warning restore 612, 618
        }
    }
}
