<Project Sdk="Microsoft.NET.Sdk.Web">
  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <RootNamespace>Sub2ApiReport.Api</RootNamespace>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.OpenApi" />
    <PackageReference Include="Microsoft.Extensions.Diagnostics.HealthChecks.EntityFrameworkCore" />
    <PackageReference Include="Quartz.AspNetCore" />
    <PackageReference Include="Quartz.Serialization.SystemTextJson" />
    <PackageReference Include="Serilog.AspNetCore" />
    <PackageReference Include="Serilog.Formatting.Compact" />
  </ItemGroup>
  <ItemGroup>
    <ProjectReference Include="..\Sub2ApiReport.Application\Sub2ApiReport.Application.csproj" />
    <ProjectReference Include="..\Sub2ApiReport.Infrastructure\Sub2ApiReport.Infrastructure.csproj" />
  </ItemGroup>
</Project>
